language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pybuilder
- pyb install_dependencies
script:
- pyb run_unit_tests -v
deploy:
  provider: pypi
  username: ingofruend
  password:
    secure: BnOQwH0r8t+foa/ySROR2fMZ94jBN5qZo1//PLimPLdB6B1XXfpXKiJIyw3c3BZcexrzNoe6g4YV6AvRvUFTCPJGqJaKLByGVe5HlbazdDz3mAfmV/BUNWDvEirKdEZil2yHcjahojaE2U7FkWu3P8VN1h+b9ob7fV9nzaz7CnK0vfHK6YTvUJzDaNIYq6aZtHdfTn8L+KQkRh2BuIOj5YwMz+nBTlJyqCwtKVt5/Bllijdyg36xgreNx0Vmv4nfz/eG5wLermzxogrfXM9tEv4Cih/WQRhpAszZHy+CMGi5l6FbyL5GwoXUalHv7uTLoVT4utfGrg66w0kUUbKuRN0bp2DLCB8p6mtxcj0jh5l9kXuxjwbpDPe1+BzHqWl8Hnb1J6W1ZUnIUBFYQv99EIsFnPyAimPbpe88lVArF1UxqruHGw+QO7AxuNs1A1yTHG3EszoysDofint5UK+T43sUA145BUESzV//QJSWT405QTMhNrfP4Su14gcDDXtcrRG39gwOMfGJZUdwpHr9BfU8x37K6zsqHyN3/qxTtDvt2BIiST/kVqotbrfcU/iotdgFUb2QNzqks64fD8DFUCXzCBt5TGrVRPtFrbdE+Pc4ue1V4qIwHsyI/t7vPd8tLQ3tr8EWwrnWXbjbn2fFyb/pldZqCqhzxvXbOKumDEg=
  on:
    branch: master
